### PR TITLE
Wheels for Python 3.8 and more

### LINKED ISSUE #98: Python 3.8 wheels are not available
Title says it all.

Dropping Python 3.5 wheels could also occur as part of this fix.

### PR DESCRIPTION
**Pull request by internaut**
This PR should allow to produce Python wheels for Python 3.6 to 3.8 on all platforms (Ubuntu, MacOS, Windows). This should fix #98.

- tests pass for Python 3.6 to 3.8 on all platforms (Ubuntu, MacOS, Windows)
- remove leftovers from (now dropped) Python 2.7 compatibility
- make flake8 pass

### CODE REVIEW

**Comment by internaut** [comment]
I decided to publish my fork on PyPI with wheels for Python 3.6 to 3.8 on all platforms (Ubuntu, MacOS, Windows), since lda is a dependency of one of my projects and I need it running on Python 3.8.

See https://pypi.org/project/ldafork/. You can install it via `pip install -U ldafork`.

**Comment by ariddell** [comment]
I'm really sorry I missed this. My emails were not being received.

I would be happy to merge this if you can split things up a couple of different pull requests. One PR should narrowly deal with the new Python versions (dropping Python 2.7 is fine).

If you don't have time, I might be able to do some of this.

**Comment by internaut** [comment]
No problem, happy to hear the project is still alive :)

Regarding splitting up into several PRs: I'll be on vacation soon until end of August, so unfortunately I won't have time for this until maybe September.

**Comment by ariddell** [comment]
I think I got most of these changes. Appveyor fixes may still be missing.

**Comment by ariddell** [comment]
Python 3.8 wheels are available.

**Comment by internaut** [comment]
Was integrated by @ariddell.

**Pull request closed without merging**
